/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import java.awt.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class JF_MuonSach extends javax.swing.JFrame {

    /**
     * Creates new form JF_MuonSach
     */
    public JF_MuonSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMuonSach = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btKTraDG = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaDG = new javax.swing.JTextField();
        txtTenDG = new javax.swing.JTextField();
        txtSLSachDangMuon = new javax.swing.JTextField();
        txtSLSachQuanHan = new javax.swing.JTextField();
        lbCheckMaDG = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btKTraTuaSach = new javax.swing.JButton();
        txtTenSachTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongTinSachMuon = new javax.swing.JTable();
        btMuonSach = new javax.swing.JButton();
        DS_SachMuon = new javax.swing.JScrollPane();
        jTextAreaMS = new javax.swing.JTextArea();
        btXoaSM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMuonSach.setBackground(new java.awt.Color(255, 255, 255));
        pnMuonSach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(226, 137, 95));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý mượn sách");

        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(93, 151, 175));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), null, new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã đọc giả");

        btKTraDG.setBackground(new java.awt.Color(51, 143, 144));
        btKTraDG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btKTraDG.setForeground(new java.awt.Color(255, 255, 255));
        btKTraDG.setToolTipText("");
        btKTraDG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btKTraDG.setLabel("Kiểm tra");
        btKTraDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKTraDGActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên đọc giả");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng sách đang mượn");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng sách quá hạn");

        txtMaDG.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtMaDG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTenDG.setEditable(false);
        txtTenDG.setBackground(new java.awt.Color(204, 204, 204));
        txtTenDG.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTenDG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSLSachDangMuon.setEditable(false);
        txtSLSachDangMuon.setBackground(new java.awt.Color(204, 204, 204));
        txtSLSachDangMuon.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSLSachDangMuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSLSachQuanHan.setEditable(false);
        txtSLSachQuanHan.setBackground(new java.awt.Color(204, 204, 204));
        txtSLSachQuanHan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSLSachQuanHan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCheckMaDG.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbCheckMaDG.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSLSachQuanHan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTenDG, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDG))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbCheckMaDG))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btKTraDG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSLSachDangMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtMaDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbCheckMaDG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btKTraDG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLSachDangMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSLSachQuanHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 191, 161));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 204), null));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nhập tên sách muốn mượn");

        btKTraTuaSach.setBackground(new java.awt.Color(0, 153, 153));
        btKTraTuaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btKTraTuaSach.setForeground(new java.awt.Color(255, 255, 255));
        btKTraTuaSach.setToolTipText("");
        btKTraTuaSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btKTraTuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKTraTuaSachActionPerformed(evt);
            }
        });

        txtTenSachTimKiem.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTenSachTimKiem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableThongTinSachMuon.setBackground(new java.awt.Color(175, 235, 225));
        tableThongTinSachMuon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        tableThongTinSachMuon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableThongTinSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableThongTinSachMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThongTinSachMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableThongTinSachMuon);

        btMuonSach.setBackground(new java.awt.Color(51, 143, 144));
        btMuonSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMuonSach.setForeground(new java.awt.Color(255, 255, 255));
        btMuonSach.setText("Mượn sách");
        btMuonSach.setToolTipText("");
        btMuonSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMuonSachActionPerformed(evt);
            }
        });

        jTextAreaMS.setColumns(20);
        jTextAreaMS.setRows(5);
        DS_SachMuon.setViewportView(jTextAreaMS);

        btXoaSM.setBackground(new java.awt.Color(51, 143, 144));
        btXoaSM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btXoaSM.setForeground(new java.awt.Color(255, 255, 255));
        btXoaSM.setText("Xóa sách");
        btXoaSM.setToolTipText("");
        btXoaSM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoaSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaSMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btXoaSM, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))
                        .addComponent(DS_SachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(txtTenSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btKTraTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(251, 251, 251))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtTenSachTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btKTraTuaSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(DS_SachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btXoaSM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pnMuonSachLayout = new javax.swing.GroupLayout(pnMuonSach);
        pnMuonSach.setLayout(pnMuonSachLayout);
        pnMuonSachLayout.setHorizontalGroup(
            pnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMuonSachLayout.createSequentialGroup()
                .addGroup(pnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMuonSachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMuonSachLayout.setVerticalGroup(
            pnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMuonSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        JF_Menu home = new JF_Menu();

        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btKTraDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKTraDGActionPerformed

        String tenDG = null; String sachDangMuon=null; String sachQuaHan=null;
        try {
            tenDG = MuonSachDAO.Instance().getTenDG(txtMaDG.getText());
            sachDangMuon = MuonSachDAO.Instance().getSLSachDangMuon(txtMaDG.getText());
            sachQuaHan = MuonSachDAO.Instance().getSLSachQuaHan(txtMaDG.getText());
            //if(tenDG==null) System.out.println("MaDG SAI!");
        } catch (SQLException ex) {
            System.out.println("Loi button KtraDG");
        }
        txtTenDG.setText(tenDG);
        txtSLSachDangMuon.setText(sachDangMuon);
        txtSLSachQuanHan.setText(sachQuaHan);
        soSachDangMuon = Integer.parseInt(sachDangMuon);
        maDG = txtMaDG.getText();
        System.out.println("MaDG: "+maDG);

    }//GEN-LAST:event_btKTraDGActionPerformed

    private void btKTraTuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKTraTuaSachActionPerformed
        //        if(txtMaDG.getText().equals("") || lbCheckMaDG.getText().equals("MaDG không tồn tại!")){
            //            JOptionPane.showMessageDialog(rootPane, "Chọn thon tin độc giả cần mượn sách trước!\n");
            //        }
        if(txtTenDG.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Thông tin đọc giả chưa có hoặc sai\n Kiểm tra lại trước!");
        }
        else{
            DefaultTableModel tabModel = (DefaultTableModel) tableThongTinSachMuon.getModel();
            tabModel.setRowCount(0);

            List<MuonSachDTO> list  = MuonSachDAO.Instance().getTableTimMuonSach(txtTenSachTimKiem.getText());
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Không tìm được quyển nào cho tựa sách này!\n Thử lại!");
            }
            list.forEach((item) -> {
                tabModel.addRow(new Object[]{
                    item.getMaCS(), item.getTenCS(), item.getNgonNgu(), item.getTaiBan(), item.getTrangThai()
                });
            });
        }

    }//GEN-LAST:event_btKTraTuaSachActionPerformed

    private void tableThongTinSachMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThongTinSachMuonMouseClicked
        if(evt.getClickCount() == 2){
            int index = tableThongTinSachMuon.getSelectedRow();
            TableModel model = tableThongTinSachMuon.getModel();
            MuonSachDTO data = new MuonSachDTO();
            data.setTrangThai(model.getValueAt(index, 4).toString());
            if("Đang cho mượn".equals(data.getTrangThai())){
                JOptionPane.showMessageDialog(null, "Sách này đang cho người khác mượn\n chọn quyển khác!");
            }
            else
            {
                data.setMaCS(model.getValueAt(index, 0).toString());
                data.setTenCS(model.getValueAt(index, 1).toString());
                data.setNgonNgu(model.getValueAt(index, 2).toString());
                data.setTaiBan(model.getValueAt(index, 3).toString());
                int  n = soSachDangMuon++;

                if( n > MuonSachDAO.Instance().getSoSachMuonToiDa(maDG)){
                    JOptionPane.showMessageDialog(null, "Đã quá số sách tối đa được mượn!\n");
                    soSachDangMuon--;
                }
                else{
                    if(listMaCSMuon.contains(data.getMaCS())){
                        JOptionPane.showMessageDialog(rootPane, "Sách này đã có trong danh sách mượn!\n ");
                    }
                    else{
                        listMaCSMuon.add(data.getMaCS());
                        listMuon.add(data);
                        String str = new String();
                        for (MuonSachDTO i : listMuon) {
                            str += i.getMaCS()+"\t"+i.getTenCS()+"\n";
                        }
                        jTextAreaMS.setText(str);
                    }
                }
            }
        }
    }//GEN-LAST:event_tableThongTinSachMuonMouseClicked

    private void btMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMuonSachActionPerformed
        if(listMaCSMuon.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Chưa có cuốn nào trong danh sách mượn!\n ");
        }
        else{
            for(String x : listMaCSMuon){
                MuonSachDAO.Instance().insertMuonSach(maDG, x);
            }

            JOptionPane.showMessageDialog(rootPane, "Thành công!\n ");
            listMuon = new ArrayList<>();
            listMaCSMuon = new ArrayList<>();
            jTextAreaMS.setText(null);

            btKTraDGActionPerformed(evt);
            btKTraTuaSachActionPerformed(evt);
        }
    }//GEN-LAST:event_btMuonSachActionPerformed

    private void btXoaSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaSMActionPerformed
        listMuon.remove(listMuon.size()-1);
        listMaCSMuon.remove(listMaCSMuon.size()-1);
        String str = new String();
        for (MuonSachDTO i : listMuon) {
            str += i.getMaCS()+"\t"+i.getTenCS()+"\n";
        }
        jTextAreaMS.setText(str);
        soSachDangMuon--;
    }//GEN-LAST:event_btXoaSMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_MuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_MuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_MuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_MuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_MuonSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DS_SachMuon;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btKTraDG;
    private javax.swing.JButton btKTraTuaSach;
    private javax.swing.JButton btMuonSach;
    private javax.swing.JButton btXoaSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMS;
    private javax.swing.JLabel lbCheckMaDG;
    private javax.swing.JPanel pnMuonSach;
    private javax.swing.JTable tableThongTinSachMuon;
    private javax.swing.JTextField txtMaDG;
    private javax.swing.JTextField txtSLSachDangMuon;
    private javax.swing.JTextField txtSLSachQuanHan;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtTenSachTimKiem;
    // End of variables declaration//GEN-END:variables
}
